"""add background_sample to trained_models

Revision ID: 3c3ca6d9a8cf
Revises: 6a6781a331ed
Create Date: 2026-07-25 22:43:45.712042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c3ca6d9a8cf'
down_revision: Union[str, Sequence[str], None] = '6a6781a331ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trained_models', sa.Column('background_sample', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trained_models', 'background_sample')
    # ### end Alembic commands ###
