"""add target_column and problem_type to datasets

Revision ID: b55cd3d9bfc6
Revises: 8ac3e32df414
Create Date: 2026-07-24 17:11:51.299196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55cd3d9bfc6'
down_revision: Union[str, Sequence[str], None] = '8ac3e32df414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('target_column', sa.String(), nullable=True))
    op.add_column('datasets', sa.Column('problem_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'problem_type')
    op.drop_column('datasets', 'target_column')
    # ### end Alembic commands ###
